[package]
name = "kepler"
version = "1.0.0"
authors = ["Exein <engineering@exein.io>"]
edition = "2018"


[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.1.5"
cpe = "0.1.1"
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
flate2 = "1.0.22"
log = "0.4.14"
r2d2 = "0.8.9"
r2d2-diesel = "1.0.0"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["blocking"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
version-compare = "0.0.13"
lru = "0.7.3"
lazy_static = "1.4.0"
diesel_json = "0.1.1"
actix-web = "4.0.1"
actix-cors = "0.6.0"
tracing-log = "0.1.2"
tracing = "0.1.31"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
tracing-actix-web = "0.5.1"
anyhow = "1.0.55"
diesel_migrations = "1.4.0"
